package zmaster587.advancedRocketry.world;

import net.minecraft.init.Biomes;
import net.minecraft.util.WeightedRandom;
import net.minecraft.world.WorldType;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;
import net.minecraftforge.common.BiomeManager.BiomeEntry;

import java.util.ArrayList;
import java.util.List;

public class GenLayerBiomePlanet extends GenLayer {

    private final List<BiomeEntry> biomeEntries;
    int biomeLimiter = -1;
    private List<Biome> biomes;

    public GenLayerBiomePlanet(long seed, GenLayer parent, WorldType worldType) {
        this(seed, parent, worldType, new ArrayList<>());
    }

    public GenLayerBiomePlanet(long seed, GenLayer parent, WorldType worldType, List<BiomeEntry> biomeEntries) {
        super(seed);
        this.parent = parent;
        this.biomeEntries = biomeEntries;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    @Override
    public int[] getInts(int p_75904_1_, int p_75904_2_, int p_75904_3_, int p_75904_4_) {
        //int[] aint = this.parent.getInts(p_75904_1_, p_75904_2_, p_75904_3_, p_75904_4_);
        int[] aint1 = IntCache.getIntCache(p_75904_3_ * p_75904_4_);

        for (int i1 = 0; i1 < p_75904_4_; ++i1) {
            for (int j1 = 0; j1 < p_75904_3_; ++j1) {
                this.initChunkSeed(j1 + p_75904_1_, i1 + p_75904_2_);

                aint1[j1 + i1 * p_75904_3_] = Biome.getIdForBiome(getWeightedBiomeEntry().biome);

            }
        }

        //TODO: DEBUG:
        //Arrays.fill(aint1, BiomeGenBase.desert.biomeID);

        return aint1;
    }

    protected BiomeEntry getWeightedBiomeEntry() {
        if (this.biomeEntries == null || this.biomeEntries.isEmpty()) {
            return new BiomeEntry(Biomes.OCEAN, 100);
        }
        int totalWeight = WeightedRandom.getTotalWeight(this.biomeEntries);
        int weight = nextInt(totalWeight);
        return WeightedRandom.getRandomItem(this.biomeEntries, weight);
    }
}
