package zmaster587.advancedRocketry.world;

import net.minecraft.init.Biomes;
import net.minecraft.util.WeightedRandom;
import net.minecraft.world.WorldType;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;
import net.minecraftforge.common.BiomeManager.BiomeEntry;

import java.util.Collections;
import java.util.List;

public class GenLayerBiomePlanet extends GenLayer {

    private static volatile List<BiomeEntry> legacyBiomeEntries = Collections.emptyList();
    private final List<BiomeEntry> biomeEntries;
    private final boolean useLegacyBiomeEntries;

    int biomeLimiter = -1;
    private List<Biome> biomes;

    public GenLayerBiomePlanet(long seed, GenLayer parent, WorldType worldType) {
        super(seed);
        this.parent = parent;
        this.biomeEntries = Collections.emptyList();
        this.useLegacyBiomeEntries = true;
    }

    public GenLayerBiomePlanet(long seed, GenLayer parent, WorldType worldType, List<BiomeEntry> biomeEntries) {
        super(seed);
        this.parent = parent;
        this.biomeEntries = biomeEntries == null ? Collections.emptyList() : biomeEntries;
        this.useLegacyBiomeEntries = false;
    }

    /**
     * Legacy compatibility for callers compiled against older AR versions.
     * Current AR biome layers receive their biome list in the constructor.
     */
    @Deprecated
    public static synchronized void setupBiomesForUse(List<BiomeEntry> entries) {
        legacyBiomeEntries = entries == null ? Collections.emptyList() : entries;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    @Override
    public int[] getInts(int p_75904_1_, int p_75904_2_, int p_75904_3_, int p_75904_4_) {
        //int[] aint = this.parent.getInts(p_75904_1_, p_75904_2_, p_75904_3_, p_75904_4_);
        int[] aint1 = IntCache.getIntCache(p_75904_3_ * p_75904_4_);

        for (int i1 = 0; i1 < p_75904_4_; ++i1) {
            for (int j1 = 0; j1 < p_75904_3_; ++j1) {
                this.initChunkSeed(j1 + p_75904_1_, i1 + p_75904_2_);

                aint1[j1 + i1 * p_75904_3_] = Biome.getIdForBiome(getWeightedBiomeEntry().biome);

            }
        }
        return aint1;
    }

    protected BiomeEntry getWeightedBiomeEntry() {
        List<BiomeEntry> entries = this.useLegacyBiomeEntries ? legacyBiomeEntries : this.biomeEntries;
        if (entries.isEmpty()) {
            return new BiomeEntry(Biomes.OCEAN, 100);
        }
        int totalWeight = WeightedRandom.getTotalWeight(entries);
        int weight = nextInt(totalWeight);
        return WeightedRandom.getRandomItem(entries, weight);
    }
}